use std::fmt::Display;

#[derive(Debug, Clone, PartialEq)]
pub enum Tags {
    A,
    Body,
    Br,
    Button,
    Code,
    Comment,
    Div,
    Doctype,
    Footer,
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    Head,
    Header,
    Html,
    I,
    Input,
    Img,
    Label,
    Li,
    Link,
    Meta,
    Nav,
    Ol,
    P,
    Pre,
    Script,
    Span,
    Table,
    Thead,
    Tbody,
    Th,
    Tr,
    Td,
    Title,
    Ul,
}
impl Display for Tags {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Tags::A => write!(f, "a"),
            Tags::Body => write!(f, "body"),
            Tags::Br => write!(f, "br"),
            Tags::Button => write!(f, "button"),
            Tags::Code => write!(f, "code"),
            Tags::Comment => write!(f, "!--"),
            Tags::Div => write!(f, "div"),
            Tags::Doctype => write!(f, "!DOCTYPE"),
            Tags::Footer => write!(f, "footer"),
            Tags::H1 => write!(f, "h1"),
            Tags::H2 => write!(f, "h2"),
            Tags::H3 => write!(f, "h3"),
            Tags::H4 => write!(f, "h4"),
            Tags::H5 => write!(f, "h5"),
            Tags::H6 => write!(f, "h6"),
            Tags::Head => write!(f, "head"),
            Tags::Header => write!(f, "header"),
            Tags::Html => write!(f, "html"),
            Tags::Input => write!(f, "input"),
            Tags::I => write!(f, "i"),
            Tags::Img => write!(f, "img"),
            Tags::Label => write!(f, "label"),
            Tags::Li => write!(f, "li"),
            Tags::Link => write!(f, "link"),
            Tags::Meta => write!(f, "meta"),
            Tags::Nav => write!(f, "nav"),
            Tags::Ol => write!(f, "ol"),
            Tags::P => write!(f, "p"),
            Tags::Pre => write!(f, "pre"),
            Tags::Script => write!(f, "script"),
            Tags::Span => write!(f, "span"),
            Tags::Table => write!(f, "table"),
            Tags::Thead => write!(f, "thead"),
            Tags::Tbody => write!(f, "tbody"),
            Tags::Th => write!(f, "th"),
            Tags::Tr => write!(f, "tr"),
            Tags::Td => write!(f, "td"),
            Tags::Title => write!(f, "title"),
            Tags::Ul => write!(f, "ul"),
        }
    }
}
